# Gas benchmark data - EDA

#### Maria Silva, December 2025

In [1]:
import os
import json
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sqlalchemy import create_engine

import warnings
warnings.filterwarnings("ignore")

In [2]:
# plotting theme
sns.set_theme(
    style="whitegrid", palette="Set2", rc={"figure.dpi": 500, "axes.titlesize": 15}
)

## Load data from DB

In this analysis, we are using data generated by running the [EEST benchmark suite](https://github.com/ethereum/execution-spec-tests/tree/main/tests/benchmark) with the [Nethermind benchmarking tooling](https://github.com/NethermindEth/gas-benchmarks). The database is hosted on a PostgreSQL server managed by the Nethermind team.

In [3]:
# Main directories
current_path = os.getcwd()
repo_dir = os.path.abspath(os.path.join(current_path, ".."))
data_dir = os.path.join(repo_dir, "data")

In [4]:
# Secrets for acessing xatu clickhouse and erigon
with open(os.path.join(repo_dir, "secrets.json"), "r") as file:
    secrets_dict = json.load(file)

# Credentials for gas bench postgresql
user = secrets_dict["gas_bench_username"]
password = secrets_dict["gas_bench_password"]

In [5]:
gas_bench_db_url = f"postgresql://{user}:{password}@perfnet.core.nethermind.dev:5432/monitoring"
start_date = "2025-12-16"
end_date = "2025-12-18"
query_str = f"""
SELECT *
FROM repricings
WHERE ingestion_timestamp BETWEEN '{start_date}'::timestamp AND '{end_date}'::timestamp
"""
engine = create_engine(gas_bench_db_url)
raw_df = pd.read_sql(query_str, con=engine)
raw_df

,id,client_name,ingestion_timestamp,client_version,test_title,max_mgas_s,p50_mgas_s,p95_mgas_s,p99_mgas_s,min_mgas_s,...,spec_processor_arch,spec_ram_gb,spec_cpu_model,spec_num_cpus,spec_cpu_ghz,end_time,test_duration,fcu_duration,np_duration,opcount
0,668884,nethermind,2025-12-16 17:24:48.082683+00:00,eip-7904,test_stack.py__test_dup[fork_Prague-opcount_50...,0.0,0.0,0.0,0.0,0.0,...,64bit,None,AMD EPYC 7713 64-Core Processor,32,None,NaT,0.0,0.0,0.0,NaN
1,666453,nethermind,2025-12-16 16:03:01.376948+00:00,eip-7904,test_stack.py__test_dup[fork_Prague-opcount_50...,0.0,0.0,0.0,0.0,0.0,...,64bit,None,AMD EPYC 7713 64-Core Processor,32,None,NaT,0.0,0.0,0.0,NaN
2,666596,nethermind,2025-12-16 16:07:50.490085+00:00,eip-7904,test_stack.py__test_dup[fork_Prague-opcount_50...,0.0,0.0,0.0,0.0,0.0,...,64bit,None,AMD EPYC 7713 64-Core Processor,32,None,NaT,0.0,0.0,0.0,NaN
3,666739,nethermind,2025-12-16 16:12:39.705946+00:00,eip-7904,test_stack.py__test_dup[fork_Prague-opcount_50...,0.0,0.0,0.0,0.0,0.0,...,64bit,None,AMD EPYC 7713 64-Core Processor,32,None,NaT,0.0,0.0,0.0,NaN
4,666882,nethermind,2025-12-16 16:17:28.983343+00:00,eip-7904,test_stack.py__test_dup[fork_Prague-opcount_50...,0.0,0.0,0.0,0.0,0.0,...,64bit,None,AMD EPYC 7713 64-Core Processor,32,None,NaT,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15296,666950,nethermind,2025-12-16 16:17:28.983343+00:00,eip-7904,test_comparison.py__test_comparison[fork_Pragu...,0.0,0.0,0.0,0.0,0.0,...,64bit,None,AMD EPYC 7713 64-Core Processor,32,None,NaT,0.0,0.0,0.0,NaN
15297,666951,nethermind,2025-12-16 16:17:28.983343+00:00,eip-7904,test_block_context.py__test_block_context_ops[...,0.0,0.0,0.0,0.0,0.0,...,64bit,None,AMD EPYC 7713 64-Core Processor,32,None,NaT,0.0,0.0,0.0,NaN
15298,666952,nethermind,2025-12-16 16:17:28.983343+00:00,eip-7904,test_system.py__test_create[fork_Prague-opcoun...,0.0,0.0,0.0,0.0,0.0,...,64bit,None,AMD EPYC 7713 64-Core Processor,32,None,NaT,0.0,0.0,0.0,NaN
15299,666953,nethermind,2025-12-16 16:17:28.983343+00:00,eip-7904,test_stack.py__test_push[fork_Prague-opcount_5...,0.0,0.0,0.0,0.0,0.0,...,64bit,None,AMD EPYC 7713 64-Core Processor,32,None,NaT,0.0,0.0,0.0,NaN
15300,666954,nethermind,2025-12-16 16:17:28.983343+00:00,eip-7904,test_keccak.py__test_keccak_max_permutations[f...,0.0,0.0,0.0,0.0,0.0,...,64bit,None,AMD EPYC 7713 64-Core Processor,32,None,NaT,0.0,0.0,0.0,NaN

In [6]:
raw_df["client_version"].unique()

array(['eip-7904', 'master', 'main'], dtype=object)

In [7]:
raw_df.columns

Index(['id', 'client_name', 'ingestion_timestamp', 'client_version',
       'test_title', 'max_mgas_s', 'p50_mgas_s', 'p95_mgas_s', 'p99_mgas_s',
       'min_mgas_s', 'n_samples', 'test_description', 'raw_gas_value',
       'raw_run_mgas_s', 'raw_run_duration_ms', 'raw_run_description',
       'start_time', 'spec_processor_type', 'spec_system_os',
       'spec_kernel_release', 'spec_kernel_version', 'spec_machine_arch',
       'spec_processor_arch', 'spec_ram_gb', 'spec_cpu_model', 'spec_num_cpus',
       'spec_cpu_ghz', 'end_time', 'test_duration', 'fcu_duration',
       'np_duration', 'opcount'],
      dtype='object')

In [8]:
raw_df["raw_run_description"].unique()

array(['Description not found on metadata file'], dtype=object)

## Machine specs, clients and versions

In [9]:
raw_df.groupby("client_name")["client_version"].unique()

client_name
besu                      [main]
erigon                    [main]
geth                    [master]
nethermind    [eip-7904, master]
reth                      [main]
Name: client_version, dtype: object

In [10]:
raw_df[
    [
        "spec_processor_type",
        "spec_system_os",
        "spec_kernel_release",
        "spec_kernel_version",
        "spec_machine_arch",
        "spec_processor_arch",
        "spec_ram_gb",
        "spec_cpu_model",
        "spec_num_cpus",
        "spec_cpu_ghz",
    ]
].drop_duplicates().T

                                                                     0
spec_processor_type                                             x86_64
spec_system_os                                                   Linux
spec_kernel_release                                   6.8.0-53-generic
spec_kernel_version  #55-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 17 15:3...
spec_machine_arch                                               x86_64
spec_processor_arch                                              64bit
spec_ram_gb                                                       None
spec_cpu_model                         AMD EPYC 7713 64-Core Processor
spec_num_cpus                                                       32
spec_cpu_ghz                                                      None

## Is data being aggregated?

In [11]:
raw_df["n_samples"].value_counts()

n_samples
0    13736
1     1565
Name: count, dtype: int64

Ok, we can mostly ignore the percentile columns as this table does not seem to be aggregating data

## Opcode counts

In [12]:
raw_df["opcount"].value_counts()

opcount
50000000.0     871
100000000.0    234
30000000.0     195
1600000.0       91
25000000.0      69
10000000.0      65
20000000.0      65
7000.0          52
10000.0         48
15000000.0      39
1000.0          27
1500000.0       26
40000000.0      13
1000000.0       13
200000000.0     13
125000.0        13
70000000.0      13
4000.0          12
Name: count, dtype: int64

In [13]:
raw_df["opcount"].isna().sum()/len(raw_df)

np.float64(0.8785046728971962)

In [14]:
raw_df[raw_df["opcount"].isna()]["test_title"].drop_duplicates()

0      test_stack.py__test_dup[fork_Prague-opcount_50...
9      test_call_context.py__test_returndatacopy[fork...
10     test_bitwise.py__test_bitwise[fork_Prague-opco...
11     test_memory.py__test_memory_access[fork_Prague...
19     test_system.py__test_create[fork_Prague-opcoun...
                             ...
157    test_tx_context.py__test_call_frame_context_op...
158    test_bitwise.py__test_bitwise[fork_Prague-opco...
159    test_stack.py__test_dup[fork_Prague-opcount_50...
160    test_comparison.py__test_comparison[fork_Pragu...
161    test_block_context.py__test_block_context_ops[...
Name: test_title, Length: 143, dtype: object

🤔 Not sure what is happening with the tests that have empty opcode counts... But, we can ignore it because they are all under 7904 branch:

In [26]:
raw_df[raw_df["opcount"].isna()]["client_version"].unique()

array(['eip-7904'], dtype=object)

## Mgas/s and run times

In [16]:
raw_df[['raw_run_mgas_s', 'raw_run_duration_ms', 'raw_gas_value']].astype("float").describe()

       raw_run_mgas_s  raw_run_duration_ms  raw_gas_value
count     1565.000000         15301.000000   15301.000000
mean       577.907650            85.096057     206.431083
std       1542.209808           432.651139     150.878106
min          1.598410             0.000000       0.106202
25%        156.169270             0.000000     157.973512
50%        321.161620             0.000000     165.123512
75%        576.448500             0.000000     212.288512
max      23039.768000         18240.195000    1000.000000

In [17]:
sum(raw_df["raw_run_duration_ms"]==0.0)/len(raw_df)

0.89771910332658

89% of rows have `raw_run_duration_ms`=0 -> need to investigate what is happening there! some examples:

In [18]:
raw_df[(raw_df["raw_run_duration_ms"]==0.0)]

,id,client_name,ingestion_timestamp,client_version,test_title,max_mgas_s,p50_mgas_s,p95_mgas_s,p99_mgas_s,min_mgas_s,...,spec_processor_arch,spec_ram_gb,spec_cpu_model,spec_num_cpus,spec_cpu_ghz,end_time,test_duration,fcu_duration,np_duration,opcount
0,668884,nethermind,2025-12-16 17:24:48.082683+00:00,eip-7904,test_stack.py__test_dup[fork_Prague-opcount_50...,0.0,0.0,0.0,0.0,0.0,...,64bit,None,AMD EPYC 7713 64-Core Processor,32,None,NaT,0.0,0.0,0.0,NaN
1,666453,nethermind,2025-12-16 16:03:01.376948+00:00,eip-7904,test_stack.py__test_dup[fork_Prague-opcount_50...,0.0,0.0,0.0,0.0,0.0,...,64bit,None,AMD EPYC 7713 64-Core Processor,32,None,NaT,0.0,0.0,0.0,NaN
2,666596,nethermind,2025-12-16 16:07:50.490085+00:00,eip-7904,test_stack.py__test_dup[fork_Prague-opcount_50...,0.0,0.0,0.0,0.0,0.0,...,64bit,None,AMD EPYC 7713 64-Core Processor,32,None,NaT,0.0,0.0,0.0,NaN
3,666739,nethermind,2025-12-16 16:12:39.705946+00:00,eip-7904,test_stack.py__test_dup[fork_Prague-opcount_50...,0.0,0.0,0.0,0.0,0.0,...,64bit,None,AMD EPYC 7713 64-Core Processor,32,None,NaT,0.0,0.0,0.0,NaN
4,666882,nethermind,2025-12-16 16:17:28.983343+00:00,eip-7904,test_stack.py__test_dup[fork_Prague-opcount_50...,0.0,0.0,0.0,0.0,0.0,...,64bit,None,AMD EPYC 7713 64-Core Processor,32,None,NaT,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15296,666950,nethermind,2025-12-16 16:17:28.983343+00:00,eip-7904,test_comparison.py__test_comparison[fork_Pragu...,0.0,0.0,0.0,0.0,0.0,...,64bit,None,AMD EPYC 7713 64-Core Processor,32,None,NaT,0.0,0.0,0.0,NaN
15297,666951,nethermind,2025-12-16 16:17:28.983343+00:00,eip-7904,test_block_context.py__test_block_context_ops[...,0.0,0.0,0.0,0.0,0.0,...,64bit,None,AMD EPYC 7713 64-Core Processor,32,None,NaT,0.0,0.0,0.0,NaN
15298,666952,nethermind,2025-12-16 16:17:28.983343+00:00,eip-7904,test_system.py__test_create[fork_Prague-opcoun...,0.0,0.0,0.0,0.0,0.0,...,64bit,None,AMD EPYC 7713 64-Core Processor,32,None,NaT,0.0,0.0,0.0,NaN
15299,666953,nethermind,2025-12-16 16:17:28.983343+00:00,eip-7904,test_stack.py__test_push[fork_Prague-opcount_5...,0.0,0.0,0.0,0.0,0.0,...,64bit,None,AMD EPYC 7713 64-Core Processor,32,None,NaT,0.0,0.0,0.0,NaN
15300,666954,nethermind,2025-12-16 16:17:28.983343+00:00,eip-7904,test_keccak.py__test_keccak_max_permutations[f...,0.0,0.0,0.0,0.0,0.0,...,64bit,None,AMD EPYC 7713 64-Core Processor,32,None,NaT,0.0,0.0,0.0,NaN

They seem to be all from the same two runs:

In [19]:
raw_df[
    (raw_df["raw_run_duration_ms"] == 0.0) & (raw_df["client_version"] != "eip-7904")
]["ingestion_timestamp"].unique()

<DatetimeArray>
['2025-12-17 03:05:59.734080+00:00', '2025-12-17 04:12:16.163304+00:00']
Length: 2, dtype: datetime64[ns, UTC]

Moving on...

In [20]:
raw_df[~raw_df["raw_run_mgas_s"].isna()][
    ["test_title", "raw_run_mgas_s", "raw_run_duration_ms", "raw_gas_value"]
]

,test_title,raw_run_mgas_s,raw_run_duration_ms,raw_gas_value
12517,test_stack.py__test_dup[fork_Prague-opcount_50...,555.64450,284.66678,158.173512
12518,test_comparison.py__test_comparison[fork_Pragu...,369.04007,501.55475,185.093792
12519,test_call_context.py__test_returndatacopy[fork...,278.27280,729.65630,203.043512
12520,test_bitwise.py__test_bitwise[fork_Prague-opco...,412.15372,449.09015,185.094176
12521,test_memory.py__test_memory_access[fork_Prague...,370.87878,503.67807,186.803512
...,...,...,...,...
14228,test_account_query.py__test_ext_account_query_...,299.68274,668.34550,200.291612
14229,test_arithmetic.py__test_arithmetic[fork_Pragu...,379.31232,487.97390,185.094512
14230,test_stack.py__test_push[fork_Prague-opcount_5...,297.72183,529.26420,157.573512
14231,test_stack.py__test_dup[fork_Prague-opcount_50...,572.02020,278.26556,159.173512
14232,test_comparison.py__test_comparison[fork_Pragu...,393.05220,470.91403,185.093792

In [21]:
len(raw_df[~raw_df["raw_run_mgas_s"].isna()])/len(raw_df)

0.10228089667342004

Also need to investigate why 10% of rows have `raw_run_mgas_s` and `raw_gas_value` with different values, as both variable should be the Mgas/s performance of the test

## Parsing test titles and params

Let's see how far we get with the simple parsing:

In [22]:
title_df = raw_df[["test_title"]].drop_duplicates()
title_df["test_file"] = (
    title_df["test_title"].str.replace("tests_benchmark_", "").str.split(".py").str[0]
)
title_df["test_name"] = title_df["test_title"].str.split(".py__").str[1].str.split("[").str[0]
title_df["test_full_params"] = (
    title_df["test_title"]
    .str.split("[")
    .str[1]
    .str.split("]")
    .str[0]
)
title_df["test_fork"] = title_df["test_full_params"].str.split("fork_").str[1].str.split("-").str[0]
title_df["test_opcount"] = title_df["test_full_params"].str.split("opcount_").str[1].str.split("-").str[0]
title_df["test_opcount"] = np.where(
    title_df["test_opcount"].str[-1]=="K", 
    title_df["test_opcount"].str[:-1], 
    title_df["test_opcount"]
    ).astype("int")
title_df["test_opcode"] = title_df["test_full_params"].str.split("opcode_").str[1].str.split("-").str[0]
title_df["test_params"] = title_df["test_full_params"].str.split("benchmark_test-").str[1]
title_df

,test_title,test_file,test_name,test_full_params,test_fork,test_opcount,test_opcode,test_params
0,test_stack.py__test_dup[fork_Prague-opcount_50...,test_stack,test_dup,fork_Prague-opcount_50000K-benchmark_test-opco...,Prague,50000,DUP6,opcode_DUP6
9,test_call_context.py__test_returndatacopy[fork...,test_call_context,test_returndatacopy,fork_Prague-opcount_20000K-benchmark_test-fixe...,Prague,20000,NaN,fixed_dst_True-0 bytes
10,test_bitwise.py__test_bitwise[fork_Prague-opco...,test_bitwise,test_bitwise,fork_Prague-opcount_30000K-benchmark_test-opco...,Prague,30000,BYTE,opcode_BYTE-
11,test_memory.py__test_memory_access[fork_Prague...,test_memory,test_memory_access,fork_Prague-opcount_20000K-benchmark_test-big_...,Prague,20000,MLOAD,big_memory_expansion_True-offset_initialized_T...
19,test_system.py__test_create[fork_Prague-opcoun...,test_system,test_create,fork_Prague-opcount_7K-benchmark_test-0 bytes ...,Prague,7,CREATE2,0 bytes with value-opcode_CREATE2
...,...,...,...,...,...,...,...,...
12667,test_arithmetic.py__test_arithmetic[fork_Pragu...,test_arithmetic,test_arithmetic,fork_Prague-opcount_10K-benchmark_test-opcode_...,Prague,10,SMOD,opcode_SMOD-
12675,test_arithmetic.py__test_mod[fork_Prague-opcou...,test_arithmetic,test_mod,fork_Prague-opcount_10K-benchmark_test-opcode_...,Prague,10,MOD,opcode_MOD-mod_bits_127
12681,test_arithmetic.py__test_arithmetic[fork_Pragu...,test_arithmetic,test_arithmetic,fork_Prague-opcount_10K-benchmark_test-opcode_...,Prague,10,MOD,opcode_MOD-
12732,test_keccak.py__test_keccak_max_permutations[f...,test_keccak,test_keccak_max_permutations,fork_Prague-opcount_4K-benchmark_test,Prague,4,NaN,NaN
12773,test_arithmetic.py__test_mod[fork_Prague-opcou...,test_arithmetic,test_mod,fork_Prague-opcount_10K-benchmark_test-opcode_...,Prague,10,SMOD,opcode_SMOD-mod_bits_127

In [23]:
len(title_df[title_df["test_opcode"].isna()])

30

We still have 30 tests that need a different parsing. Let's see one by one:

In [24]:
title_df[title_df["test_opcode"].isna()]["test_name"].unique()

array(['test_returndatacopy', 'test_keccak_max_permutations',
       'test_blockhash', 'test_msize', 'test_pc_op',
       'test_returndatasize_zero', 'test_iszero', 'test_selfbalance',
       'test_not_op', 'test_calldatasize', 'test_mcopy', 'test_tstore',
       'test_jumpi_fallthrough', 'test_callvalue_from_origin',
       'test_gas_op', 'test_selfdestruct_initcode', 'test_codesize',
       'test_codecopy', 'test_tload', 'test_calldatacopy_from_origin',
       'test_calldataload', 'test_jumpdests', 'test_extcodecopy_warm',
       'test_returndatasize_nonzero', 'test_selfdestruct_created'],
      dtype=object)

In [25]:
full_title_df = title_df.copy()
opcodes_in_test_name_list = [
    "test_blockhash",
    "test_msize",
    "test_pc_op",
    "test_returndatasize_zero",
    "test_iszero",
    "test_selfbalance",
    "test_not_op",
    "test_calldatasize",
    "test_mcopy",
    "test_tstore",
    "test_jumpi_fallthrough",
    "test_callvalue_from_origin",
    "test_gas_op",
    "test_selfdestruct_initcode",
    "test_returndatacopy",
    "test_calldatacopy_from_origin",
    "test_calldataload",
    "test_jumpdests",
    "test_extcodecopy_warm",
    "test_returndatasize_nonzero",
    "test_codesize",
    "test_codecopy",
    "test_tload",
    "test_selfdestruct_created",
    "test_keccak_max_permutations",
]
full_title_df["test_opcode"] = np.where(
    full_title_df["test_name"].isin(opcodes_in_test_name_list),
    full_title_df["test_name"].str.split("_").str[1].str.upper(),
    full_title_df["test_opcode"],
)
full_title_df[full_title_df["test_name"].isin(opcodes_in_test_name_list)]

,test_title,test_file,test_name,test_full_params,test_fork,test_opcount,test_opcode,test_params
9,test_call_context.py__test_returndatacopy[fork...,test_call_context,test_returndatacopy,fork_Prague-opcount_20000K-benchmark_test-fixe...,Prague,20000,RETURNDATACOPY,fixed_dst_True-0 bytes
21,test_keccak.py__test_keccak_max_permutations[f...,test_keccak,test_keccak_max_permutations,fork_Prague-opcount_1K-benchmark_test,Prague,1,KECCAK,NaN
27,test_block_context.py__test_blockhash[fork_Pra...,test_block_context,test_blockhash,fork_Prague-opcount_10000K-benchmark_test-curr...,Prague,10000,BLOCKHASH,current_block
29,test_memory.py__test_msize[fork_Prague-opcount...,test_memory,test_msize,fork_Prague-opcount_100000K-benchmark_test-mem...,Prague,100000,MSIZE,mem_size_1
32,test_control_flow.py__test_pc_op[fork_Prague-o...,test_control_flow,test_pc_op,fork_Prague-opcount_100000K-benchmark_test,Prague,100000,PC,NaN
37,test_call_context.py__test_returndatasize_zero...,test_call_context,test_returndatasize_zero,fork_Prague-opcount_100000K-benchmark_test,Prague,100000,RETURNDATASIZE,NaN
40,test_comparison.py__test_iszero[fork_Prague-op...,test_comparison,test_iszero,fork_Prague-opcount_30000K-benchmark_test,Prague,30000,ISZERO,NaN
42,test_account_query.py__test_selfbalance[fork_P...,test_account_query,test_selfbalance,fork_Prague-opcount_40000K-benchmark_test-cont...,Prague,40000,SELFBALANCE,contract_balance_1
43,test_bitwise.py__test_not_op[fork_Prague-opcou...,test_bitwise,test_not_op,fork_Prague-opcount_30000K-benchmark_test,Prague,30000,NOT,NaN
45,test_call_context.py__test_calldatasize[fork_P...,test_call_context,test_calldatasize,fork_Prague-opcount_100000K-benchmark_test-cal...,Prague,100000,CALLDATASIZE,calldata_length_10000
57,test_memory.py__test_mcopy[fork_Prague-opcount...,test_memory,test_mcopy,fork_Prague-opcount_15000K-benchmark_test-fixe...,Prague,15000,MCOPY,fixed_src_dst_True-0 bytes
66,test_storage.py__test_tstore[fork_Prague-opcou...,test_storage,test_tstore,fork_Prague-opcount_1500K-benchmark_test-fixed...,Prague,1500,TSTORE,fixed_value_False-fixed_key_False
67,test_control_flow.py__test_jumpi_fallthrough[f...,test_control_flow,test_jumpi_fallthrough,fork_Prague-opcount_15000K-benchmark_test,Prague,15000,JUMPI,NaN
73,test_call_context.py__test_callvalue_from_orig...,test_call_context,test_callvalue_from_origin,fork_Prague-opcount_50000K-benchmark_test-non_...,Prague,50000,CALLVALUE,non_zero_value_True
81,test_control_flow.py__test_gas_op[fork_Prague-...,test_control_flow,test_gas_op,fork_Prague-opcount_100000K-benchmark_test,Prague,100000,GAS,NaN
82,test_block_context.py__test_blockhash[fork_Pra...,test_block_context,test_blockhash,fork_Prague-opcount_10000K-benchmark_test-bloc...,Prague,10000,BLOCKHASH,block_256
84,test_system.py__test_selfdestruct_initcode[for...,test_system,test_selfdestruct_initcode,fork_Prague-opcount_1K-state_test-value_bearin...,Prague,1,SELFDESTRUCT,NaN
94,test_account_query.py__test_codesize[fork_Prag...,test_account_query,test_codesize,fork_Prague-opcount_100000K-benchmark_test,Prague,100000,CODESIZE,NaN
104,test_account_query.py__test_codecopy[fork_Prag...,test_account_query,test_codecopy,fork_Prague-opcount_15000K-benchmark_test-fixe...,Prague,15000,CODECOPY,fixed_src_dst_True-0 bytes
105,test_storage.py__test_tload[fork_Prague-opcoun...,test_storage,test_tload,fork_Prague-opcount_1500K-benchmark_test-fixed...,Prague,1500,TLOAD,fixed_value_True-fixed_key_True
107,test_block_context.py__test_blockhash[fork_Pra...,test_block_context,test_blockhash,fork_Prague-opcount_10000K-benchmark_test-random,Prague,10000,BLOCKHASH,random
108,test_block_context.py__test_blockhash[fork_Pra...,test_block_context,test_blockhash,fork_Prague-opcount_10000K-benchmark_test-block_1,Prague,10000,BLOCKHASH,block_1
119,test_call_context.py__test_calldatacopy_from_o...,test_call_context,test_calldatacopy_from_origin,fork_Prague-opcount_20000K-benchmark_test-non_...,Prague,20000,CALLDATACOPY,non_zero_data_False-fixed_src_dst_True-0 bytes
128,test_call_context.py__test_calldataload[fork_P...,test_call_context,test_calldataload,fork_Prague-opcount_70000K-benchmark_test-zero...,Prague,70000,CALLDATALOAD,zero-loop
132,test_control_flow.py__test_jumpdests[fork_Prag...,test_control_flow,test_jumpdests,fork_Prague-opcount_200000K-benchmark_test,Prague,200000,JUMPDESTS,NaN
133,test_account_query.py__test_extcodecopy_warm[f...,test_account_query,test_extcodecopy_warm,fork_Prague-opcount_1000K-benchmark_test-512,Prague,1000,EXTCODECOPY,512
136,test_call_context.py__test_returndatasize_nonz...,test_call_context,test_returndatasize_nonzero,fork_Prague-opcount_50000K-benchmark_test-retu...,Prague,50000,RETURNDATASIZE,returned_size_0-return_data_style_ReturnDataSt...
145,test_block_context.py__test_blockhash[fork_Pra...,test_block_context,test_blockhash,fork_Prague-opcount_10000K-benchmark_test-genesis,Prague,10000,BLOCKHASH,genesis
147,test_system.py__test_selfdestruct_created[fork...,test_system,test_selfdestruct_created,fork_Prague-opcount_1K-state_test-value_bearin...,Prague,1,SELFDESTRUCT,NaN
12732,test_keccak.py__test_keccak_max_permutations[f...,test_keccak,test_keccak_max_permutations,fork_Prague-opcount_4K-benchmark_test,Prague,4,KECCAK,NaN

Ok, the opcode names are now complete!